export{default as LandingPage } from './LandingPage/LandingPage';
export{default as Cover } from './0.Cover/Cover';
export{default as Brands } from './6.Brands/Brands';
export{default as Benefits } from './3.Benefits/Benefits';
export{default as Testimonials } from './5.Testimonials/Testimonials'
export{default as Footer } from './7.Footer/Footer'
export{default as Partners } from './4.Partners/Partners'
export{default as Navigation } from './1.Navigation/Navigation'
export{default as Need } from './2.Need/Need'
